Don't crash if empty edge when plotting runtime statistics.
If the job finished without any edge, then it used to crash like this:

Traceback (most recent call last):
  File "/Users/rwest/Code/RMG-Py/rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 549, in execute
    self.saveEverything()
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 801, in saveEverything
    self.notify()
  File "/Users/rwest/Code/RMG-Py/rmgpy/util.py", line 106, in notify
    observer.update(self)
  File "/Users/rwest/Code/RMG-Py/rmgpy/stats.py", line 85, in update
    self.update_execution(rmg)
  File "/Users/rwest/Code/RMG-Py/rmgpy/stats.py", line 119, in update_execution
    self.generateExecutionPlots(rmg)
  File "/Users/rwest/Code/RMG-Py/rmgpy/stats.py", line 207, in generateExecutionPlots
    ax1.loglog(rmg.execTime, self.edgeSpeciesCount, 'o-b')
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1562, in loglog
    l = self.plot(*args, **kwargs)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1428, in plot
    self.autoscale_view(scalex=scalex, scaley=scaley)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2197, in autoscale_view
    y0, y1 = ylocator.view_limits(y0, y1)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/matplotlib/ticker.py", line 1613, in view_limits
    "Data has no positive values, and therefore can not be "
ValueError: Data has no positive values, and therefore can not be log-scaled.


Now it doesn't.